---

env: local
start_time: 20:00
stop_time: 00:00
batteries:
  - name: battery1
    url: https://example.battery1/api
    token: auth-token1
    enabled: true
    capacity_limit: 10000
    power_limit: 500
  - name: battery2
    url: https://example.battery2/api
    token: auth-token2
    enabled: false
    capacity_limit: 5000
    power_limit: 250
  - name: battery3
    url: https://example.battery3/api
    token: auth-token3
    enabled: true
    capacity_limit: 5000
    power_limit: 250